spring.application.name=usermanagementmicroservice

# External Render PostgreSQL 
spring.datasource.url=jdbc:postgresql://dpg-d7frvnq8qa3s73do8en0-a.singapore-postgres.render.com:5432/ams_14tr
spring.datasource.username=ams_14tr_user
spring.datasource.password=ZzY2glNbkiZnTeNNNInx41jC3lliZhKl
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chimikdolkar17@gmail.com
spring.mail.password=gast aumx cqul obji
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional (can remove, auto-detected)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.main.allow-bean-definition-overriding=true
# spring.config.import=optional:application.properties

eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/