spring.application.name=usermanagementmicroservice

# External Render PostgreSQL (IMPORTANT: use external hostname)
spring.datasource.url=jdbc:postgresql://dpg-d6u2do9j16oc73fma5r0-a.singapore-postgres.render.com:5432/ams_db_qrv5
spring.datasource.username=ams_admin
spring.datasource.password=swsKsQXsPpmXPRUzwIT7fffBCqbLUqVN
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (can remove, auto-detected)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.main.allow-bean-definition-overriding=true
# spring.config.import=optional:application.properties